### ISSUE TITLE
Monica's issues starting the localhost 

### ISSUE THREAD

**Issue by guomon** [nickdotreid/opioid-mat-decision-aid#1]
Hopefully a quick fix and I'm missing something obvious in a step to get ng serve to work again. I'm attaching 
Tried: calling ng serve in both the main file and one file level down
Tried then: installing angular again? But my account does have administrator access

![log2](https://user-images.githubusercontent.com/6990369/46254927-fbbf2700-c44b-11e8-9c78-3134d21bee34.PNG)
![log1](https://user-images.githubusercontent.com/6990369/46254928-fbbf2700-c44b-11e8-8f58-f0b58c7f9631.PNG)

the errors I'm running into

**Comment by nickdotreid** [comment]
@guomon - From looking at what you posted, I'm guessing you're not in the client directory.

try:
```
$ cd ~/opioid-mat-decision-aid/client
$ ng serve
```

The second screenshot you posted is a classic not having permission problem. If you need to re-install the angular command line (which I don't think you need to??) -- you need to use sudo when using npm "install -g".

```
$ sudo npm install -g @angular/cli
```

Let me know if this helps!

**Comment by guomon** [comment]
It works great! Thank you for my life. I had to do something extra and install @angular-devkit/build-angular as dev dependency, but then it worked.
